type Subdisciplines = {
  [key: string]: string[];
};

export const subdisciplines: Subdisciplines = {
  Portugues: [
    "Gramática",
    "Ortografia",
    "Morfologia",
    "Sintaxe",
    "Semântica",
    "Literatura Brasileira",
    "Literatura Portuguesa",
    "Literatura Comparada",
    "Redação",
    "Interpretação de Texto",
    "Produção Textual",
    "Leitura e Compreensão",
    "Análise Literária",
    "Figuras de Linguagem",
    "História da Língua Portuguesa",
    "Estudo de Gêneros Textuais",
    "Fonologia",
    "Estilística",
    "Sociolinguística",
    "Linguística Geral",
  ],
  Matematica: [
    "Aritmética",
    "Álgebra",
    "Geometria Plana",
    "Geometria Espacial",
    "Trigonometria",
    "Estatística",
    "Probabilidade",
    "Cálculo Diferencial",
    "Cálculo Integral",
    "Matemática Financeira",
    "Lógica Matemática",
    "Teoria dos Números",
    "Equações Diferenciais",
    "Geometria Analítica",
    "Análise Combinatória",
    "Funções",
    "Matemática Discreta",
    "Topologia",
    "Matemática Aplicada",
    "Modelagem Matemática",
  ],
  Ciencias: [
    "Astronomia",
    "Ecologia",
    "Ciências Ambientais",
    "Ciências da Terra",
    "Geologia",
    "Meteorologia",
    "Hidrologia",
    "Ciências do Espaço",
    "Paleontologia",
    "Oceanografia",
    "Zoologia",
    "Botânica",
    "Educação Científica",
    "Fisiologia Básica",
    "Genética e Evolução",
    "Sustentabilidade",
    "Saúde e Higiene",
    "Energia e Meio Ambiente",
    "Método Científico",
    "História das Ciências",
  ],
  Historia: [
    "História Antiga",
    "História Medieval",
    "História Moderna",
    "História Contemporânea",
    "História do Brasil",
    "História da América",
    "História da África",
    "História da Ásia",
    "História Econômica",
    "História Cultural",
    "História Política",
    "História das Religiões",
    "História Militar",
    "História das Ciências",
    "História do Pensamento Político",
    "Historiografia",
    "Arqueologia",
    "Patrimônio Histórico e Cultural",
    "Movimentos Sociais",
    "Colonialismo e Pós-Colonialismo",
  ],
  Geografia: [
    "Geografia Física",
    "Geografia Humana",
    "Cartografia",
    "Geopolítica",
    "Climatologia",
    "Geomorfologia",
    "Hidrografia",
    "Biogeografia",
    "Geografia Econômica",
    "Geografia Urbana",
    "Geografia Rural",
    "Demografia",
    "Geografia Regional",
    "Geografia Ambiental",
    "Planejamento Territorial",
    "Geografia Cultural",
    "Geografia da População",
    "Sistemas de Informação Geográfica (SIG)",
    "Recursos Naturais e Meio Ambiente",
    "Globalização e Espaço Geográfico",
  ],
  EducacaoFisica: [
    "Esportes Coletivos",
    "Esportes Individuais",
    "Atletismo",
    "Ginástica",
    "Educação Motora",
    "Dança",
    "Capoeira",
    "Lutas e Artes Marciais",
    "Recreação e Lazer",
    "Fisiologia do Exercício",
    "Biomecânica",
    "Treinamento Esportivo",
    "Avaliação Física",
    "Psicologia do Esporte",
    "História da Educação Física",
    "Saúde e Bem-Estar",
    "Nutrição Esportiva",
    "Inclusão na Educação Física",
    "Jogos e Brincadeiras",
    "Metodologia da Educação Física",
  ],
  Artes: [
    "História da Arte",
    "Arte Contemporânea",
    "Artes Visuais",
    "Desenho",
    "Pintura",
    "Escultura",
    "Gravura",
    "Fotografia",
    "Arte Digital",
    "Cinema",
    "Teatro",
    "Dança",
    "Música",
    "Cenografia",
    "Arte Urbana",
    "Performance Art",
    "Ilustração",
    "Design Gráfico",
    "Estética",
    "Educação Artística",
  ],
  Ingles: [
    "Gramática",
    "Vocabulário",
    "Pronúncia",
    "Listening (Compreensão Auditiva)",
    "Reading (Compreensão de Texto)",
    "Writing (Produção Escrita)",
    "Speaking (Conversação)",
    "Inglês para Negócios",
    "Inglês Acadêmico",
    "Expressões Idiomáticas",
    "Falsos Cognatos",
    "Tradução e Interpretação",
    "Cultura dos Países de Língua Inglesa",
    "Literatura Inglesa",
    "Literatura Americana",
    "Fonética e Fonologia",
    "Técnicas de Debate e Argumentação",
    "Inglês para Viagens",
    "Inglês para Tecnologia",
    "Inglês Preparatório para Testes (TOEFL, IELTS, etc.)",
  ],
  Biologia: [
    "Citologia",
    "Histologia",
    "Anatomia Humana",
    "Fisiologia",
    "Genética",
    "Biotecnologia",
    "Ecologia",
    "Zoologia",
    "Botânica",
    "Microbiologia",
    "Imunologia",
    "Embriologia",
    "Biologia Celular",
    "Biologia Molecular",
    "Evolução",
    "Biogeografia",
    "Parasitologia",
    "Bioquímica",
    "Sistemática e Taxonomia",
    "Biologia Marinha",
  ],
  Quimica: [
    "Química Geral",
    "Química Inorgânica",
    "Química Orgânica",
    "Físico-Química",
    "Bioquímica",
    "Química Analítica",
    "Química Ambiental",
    "Eletroquímica",
    "Termoquímica",
    "Cinetica Química",
    "Radioatividade",
    "Química Industrial",
    "Polímeros",
    "Química dos Materiais",
    "Toxicologia Química",
    "Química Medicinal",
    "Química Forense",
    "Estrutura Atômica",
    "Ligação Química",
    "Reações Químicas",
  ],
  Fisica: [
    "Mecânica",
    "Cinemática",
    "Dinâmica",
    "Estática",
    "Hidrostática",
    "Termodinâmica",
    "Óptica",
    "Eletromagnetismo",
    "Ondas",
    "Acústica",
    "Física Moderna",
    "Relatividade",
    "Física Quântica",
    "Física Nuclear",
    "Astrofísica",
    "Cosmologia",
    "Física Experimental",
    "Física dos Materiais",
    "Biomoléculas e Biofísica",
    "Instrumentação Científica",
  ],
  Sociologia: [
    "Teorias Sociológicas Clássicas",
    "Teorias Sociológicas Contemporâneas",
    "Sociologia da Educação",
    "Sociologia do Trabalho",
    "Sociologia da Família",
    "Sociologia Urbana",
    "Sociologia Rural",
    "Sociologia Política",
    "Estratificação Social",
    "Movimentos Sociais",
    "Globalização e Sociedade",
    "Sociologia da Religião",
    "Sociologia da Cultura",
    "Sociologia do Consumo",
    "Métodos de Pesquisa em Sociologia",
    "Desigualdade e Exclusão Social",
    "Sociedade e Tecnologia",
    "Sociologia do Meio Ambiente",
    "Sociologia do Gênero",
    "Criminologia e Sociedade",
  ],
  Filosofia: [
    "História da Filosofia",
    "Filosofia Antiga",
    "Filosofia Medieval",
    "Filosofia Moderna",
    "Filosofia Contemporânea",
    "Metafísica",
    "Epistemologia",
    "Lógica",
    "Ética",
    "Estética",
    "Filosofia Política",
    "Filosofia da Linguagem",
    "Filosofia da Ciência",
    "Filosofia da Mente",
    "Filosofia da Religião",
    "Filosofia Existencialista",
    "Filosofia do Direito",
    "Filosofia Oriental",
    "Fenomenologia",
    "Hermenêutica",
  ],
  Outros: ["Outros"],
};
